"""Markdown renderer for Ba Zi reports."""

from __future__ import annotations

from pathlib import Path

from .calculations import compute_all
from .data_types import BaziRecord, Gender
from .interpretations import analyze_element_balance, get_day_master_profile


def render_markdown(
    record: BaziRecord,
    gender: Gender,
    output_dir: str | Path = ".",
) -> str:
    """Generate a Markdown Ba Zi report.

    Returns the path to the written file as a string.
    """
    from ..renderer.naming import generate_initials

    result = compute_all(record)
    initials = generate_initials(record.name)

    balance = analyze_element_balance(result.element_counts)
    dm_profile = get_day_master_profile(result.day_master_yin_yang, result.day_master_element)

    md = f"""# Ba Zi — Four Pillars of Destiny

**{record.name}** · Born {result.birth_date.isoformat()} · Gender: {gender.value}

> **Note:** This report uses the Chinese sexagenary cycle to compute four pillars (year, month, day, hour) and analyzes element interactions.

---

## Day Master Profile — **{dm_profile['title']}**

{dm_profile['description']}

**Strengths:** {', '.join(dm_profile['strengths'])}
**Challenges:** {', '.join(dm_profile['challenges'])}

---

## The Four Pillars

| Pillar | Stem | Branch | Hidden Stems | Area of Life |
|--------|------|--------|--------------|--------------|
| **Year (年)** | {result.year_pillar.stem_branch.stem_index} | {result.year_pillar.stem_branch.branch_index} | {result.year_pillar.hidden_stems or '—'} | Ancestors, early childhood (0-16) |
| **Month (月)** | {result.month_pillar.stem_branch.stem_index} | {result.month_pillar.stem_branch.branch_index} | {result.month_pillar.hidden_stems or '—'} | Parents, career foundation (17-32) |
| **Day (日)** | {result.day_pillar.stem_branch.stem_index} | {result.day_pillar.stem_branch.branch_index} | {result.day_pillar.hidden_stems or '—'} | Self and spouse (33-48) |
| **Hour (时)** | {result.hour_pillar.stem_branch.stem_index} | {result.hour_pillar.stem_branch.branch_index} | {result.hour_pillar.hidden_stems or '—'} | Children, later life (49+) |

---

## Element Balance

{result.element_counts}

- **Dominant:** {balance['dominant_element']} ({balance['dominant_percentage']}%)
- **Weakest:** {balance['weakest_element']} ({balance['weakest_percentage']}%)
- **Balanced:** {'Yes ✓' if balance['is_balanced'] else 'No — consider elemental remedies'}

---

## Luck Pillars (大运)

| Age Range | Years | Stem/Branch |
|-----------|-------|-------------|
"""

    for lp in result.luck_pillars:
        md += f"| Ages {lp.start_age}-{lp.start_age + 9} | {lp.year_range} | {lp.stem_branch.stem_index}/{lp.stem_branch.branch_index} |\n"

    md += f"""
---

*Generated by the Ba Zi Skill · Based on the Chinese Sexagenary Cycle*
"""

    out = Path(output_dir)
    path = out / f"{initials}_bazi.md"
    path.write_text(md, encoding="utf-8")
    return str(path)
