"""HTML renderer for numerology reports."""

from __future__ import annotations

from pathlib import Path

from .calculations import compute_all
from .data_types import NumerologyRecord
from .interpretations import format_interpretation
from .renderer import render_wheel


def _number_badge(n: int) -> str:
    """HTML badge for a number."""
    if n in (11, 22, 33):
        return f'<span class="master-badge">{n} ★</span>'
    return f'<span class="num-badge">{n}</span>'


def render_html(
    record: NumerologyRecord,
    initials: str = "",
    output_dir: str | Path = ".",
) -> str:
    """Generate a full HTML numerology report.

    Returns the path to the written file as a string.
    """
    from ..renderer.chart_writer import atomic_write

    if not initials:
        from ..renderer.naming import generate_initials
        initials = generate_initials(record.full_name)

    pyth, chald = compute_all(record)

    # Build SVG wheel inline
    svg_content = render_wheel(
        record.full_name, pyth, chald, width=600, height=750
    )

    # Helper to compare two systems side by side
    def _system_rows(core: CoreNumbers) -> str:
        cats = [
            ("life_path", core.life_path, core.life_path_breakdown),
            ("expression", core.expression, core.expression_breakdown),
            ("soul_urge", core.soul_urge, core.soul_urge_breakdown),
            ("personality", core.personality, core.personality_breakdown),
            ("birthday", core.birthday, core.birthday_breakdown),
        ]
        rows = []
        for cat, num, breakdown in cats:
            interp = format_interpretation(cat, num, breakdown)
            lines = interp.split("\n")
            title_line = lines[0] if lines else ""
            summary = lines[1] if len(lines) > 1 else ""
            rest = "\n".join(lines[2:]) if len(lines) > 2 else ""

            rows.append(f"""<div class="number-card">
  <h3>{title_line}</h3>
  <p class="summary">{summary}</p>
  <pre class="calculation">{rest}</pre>
</div>""")
        return "\n".join(rows)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Numerology Report — {record.full_name}</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #2c3e50; background: #fafbfc; }}
  h1 {{ text-align: center; color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 0.5rem; }}
  h2 {{ color: #34495e; margin-top: 2rem; }}
  .subtitle {{ text-align: center; color: #7f8c8d; font-size: 1.1rem; margin-bottom: 2rem; }}
  .wheel-container {{ text-align: center; margin: 2rem 0; }}
  .wheel-container svg {{ max-width: 100%; height: auto; }}
  .systems-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 2rem; }}
  @media (max-width: 700px) {{ .systems-grid {{ grid-template-columns: 1fr; }} }}
  .system-block {{ background: #fff; border-radius: 8px; padding: 1.5rem; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
  .system-block h3 {{ margin-top: 0; color: #2980b9; }}
  .system-block.chaldean h3 {{ color: #8e44ad; }}
  .number-card {{ margin-bottom: 1rem; padding-bottom: 1rem; border-bottom: 1px solid #ecf0f1; }}
  .number-card:last-child {{ border-bottom: none; }}
  .num-badge {{ display: inline-block; background: #3498db; color: #fff; border-radius: 50%; width: 36px; height: 36px; line-height: 36px; text-align: center; font-weight: bold; font-size: 1.1rem; }}
  .master-badge {{ display: inline-block; background: #e74c3c; color: #fff; border-radius: 50%; width: 40px; height: 40px; line-height: 40px; text-align: center; font-weight: bold; font-size: 1.1rem; animation: pulse 2s infinite; }}
  @keyframes pulse {{ 0%, 100% {{ transform: scale(1); }} 50% {{ transform: scale(1.08); }} }}
  .summary {{ color: #34495e; font-style: italic; margin: 0.25rem 0; }}
  .calculation {{ background: #f8f9fa; padding: 0.75rem; border-radius: 4px; font-size: 0.85rem; color: #6c757d; white-space: pre-wrap; margin: 0.5rem 0; }}
  .footer {{ text-align: center; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ecf0f1; color: #95a5a6; font-size: 0.85rem; }}
</style>
</head>
<body>

<h1>Numerology Report</h1>
<p class="subtitle">{record.full_name} · Born {record.date_of_birth.isoformat()}</p>

<div class="wheel-container">
{svg_content}
</div>

<h2>Pythagorean vs Chaldean — Side by Side</h2>

<div class="systems-grid">
  <div class="system-block">
    <h3>Pythagorean System</h3>
{_system_rows(pyth)}
  </div>
  <div class="system-block chaldean">
    <h3>Chaldean System</h3>
{_system_rows(chald)}
  </div>
</div>

<div class="footer">
  <p>Generated by the Numerology Skill · Both Pythagorean and Chaldean systems</p>
  <p><em>Note: Master numbers (11, 22, 33) are not reduced to single digits.</em></p>
</div>

</body>
</html>"""

    out = Path(output_dir)
    path = out / f"{initials}_numerology.html"
    atomic_write(path, html)
    return str(path)


from .data_types import CoreNumbers
