"""Markdown renderer for numerology reports."""

from __future__ import annotations

from pathlib import Path

from .calculations import compute_all
from .data_types import NumerologyRecord
from .interpretations import format_interpretation


def render_markdown(
    record: NumerologyRecord,
    initials: str = "",
    output_dir: str | Path = ".",
) -> str:
    """Generate a Markdown numerology report.

    Returns the path to the written file as a string.
    """
    from ..renderer.naming import generate_initials

    if not initials:
        initials = generate_initials(record.full_name)

    pyth, chald = compute_all(record)

    def _system_md(core, system_name: str) -> str:
        lines = [f"### {system_name}"]
        cats = [
            ("life_path", core.life_path, core.life_path_breakdown),
            ("expression", core.expression, core.expression_breakdown),
            ("soul_urge", core.soul_urge, core.soul_urge_breakdown),
            ("personality", core.personality, core.personality_breakdown),
            ("birthday", core.birthday, core.birthday_breakdown),
        ]
        for cat, num, breakdown in cats:
            interp = format_interpretation(cat, num, breakdown)
            lines.append(f"#### {cat.replace('_', ' ').title()} — **{num}**")
            # Parse the formatted interpretation
            parts = interp.split("\n")
            if parts:
                lines.append(parts[0])  # Title + number
            if len(parts) > 1:
                lines.append(parts[1])  # Summary
            if len(parts) > 2:
                for p in parts[2:]:
                    lines.append(f"> {p}")
            lines.append("")
        return "\n".join(lines)

    md = f"""# Numerology Report

**{record.full_name}** · Born {record.date_of_birth.isoformat()}

> **Note:** This report presents both Pythagorean and Chaldean systems side by side.
> Master numbers (11, 22, 33) are not reduced to single digits.

---

## Overview

| Number | Pythagorean | Chaldean |
|--------|-------------|----------|
| Life Path | {pyth.life_path} | {chald.life_path} |
| Expression | {pyth.expression} | {chald.expression} |
| Soul Urge | {pyth.soul_urge} | {chald.soul_urge} |
| Personality | {pyth.personality} | {chald.personality} |
| Birthday | {pyth.birthday} | {chald.birthday} |

---

{_system_md(pyth, "Pythagorean System")}

---

{_system_md(chald, "Chaldean System")}

---

*Generated by the Numerology Skill*
"""

    out = Path(output_dir)
    path = out / f"{initials}_numerology.md"
    path.write_text(md, encoding="utf-8")
    return str(path)
